### ISSUE TITLE
Assignment 5: Missing

### ISSUE THREAD

**Issue by RLL24187** [esteakshapin/SWR-SPRING-2021-Assignments#7]
Please complete all of the freeCodeCamp modules from Responsive Web Design through Applied Visual Design and submit a screenshot to show you completed them in a folder `a5`

**Comment by esteakshapin** [comment]
Hey sorry abt that i was attending MIT blueprint all weekend and didn't have any time to complete that. I have made it up now and will post it along with assignment 6.
